import type {
  OnboardingGeneralSettingsDto,
  OnboardingStageConfigDto,
  OnboardingFieldConfigDto,
  OnboardingDocumentRequirementDto,
  OnboardingChecklistTemplateDto,
  OnboardingConversionSettingsDto,
} from '../types/settings.types.js';

export function getDefaultGeneralSettings(
  tenantId: string,
  companyId: string,
): OnboardingGeneralSettingsDto {
  const now = new Date();
  return {
    id: `gen_sett_${companyId}`,
    tenantId,
    companyId,
    onboardingEnabled: true,
    defaultDurationDays: 30,
    idPrefix: 'NH-',
    defaultLocationId: null,
    createdAt: now,
    updatedAt: now,
  };
}

export function getDefaultStageConfigs(
  tenantId: string,
  companyId: string,
): OnboardingStageConfigDto[] {
  const now = new Date();
  return [
    {
      id: `stg_cfg_${companyId}_preboarding`,
      tenantId,
      companyId,
      stageKey: 'preboarding',
      name: 'Pre-boarding',
      description: 'Pre-boarding activities prior to day 1',
      displayOrder: 1,
      isRequired: true,
      isActive: true,
      isSystem: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: `stg_cfg_${companyId}_documents`,
      tenantId,
      companyId,
      stageKey: 'documents',
      name: 'Document Collection',
      description: 'Collection and verification of employee credentials',
      displayOrder: 2,
      isRequired: true,
      isActive: true,
      isSystem: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: `stg_cfg_${companyId}_induction`,
      tenantId,
      companyId,
      stageKey: 'induction',
      name: 'Induction & Orientation',
      description: 'Welcome session and team orientation',
      displayOrder: 3,
      isRequired: true,
      isActive: true,
      isSystem: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: `stg_cfg_${companyId}_completed`,
      tenantId,
      companyId,
      stageKey: 'completed',
      name: 'Completed',
      description: 'Onboarding process successfully finalized',
      displayOrder: 4,
      isRequired: true,
      isActive: true,
      isSystem: true,
      createdAt: now,
      updatedAt: now,
    },
  ];
}

export function getDefaultFieldConfigs(
  tenantId: string,
  companyId: string,
): OnboardingFieldConfigDto[] {
  const now = new Date();
  return [
    {
      id: `fld_cfg_${companyId}_first_name`,
      tenantId,
      companyId,
      fieldKey: 'firstName',
      label: 'First Name',
      isRequired: true,
      isEnabled: true,
      displayOrder: 1,
      isSystem: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: `fld_cfg_${companyId}_last_name`,
      tenantId,
      companyId,
      fieldKey: 'lastName',
      label: 'Last Name',
      isRequired: false,
      isEnabled: true,
      displayOrder: 2,
      isSystem: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: `fld_cfg_${companyId}_email`,
      tenantId,
      companyId,
      fieldKey: 'email',
      label: 'Work / Personal Email',
      isRequired: true,
      isEnabled: true,
      displayOrder: 3,
      isSystem: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: `fld_cfg_${companyId}_phone`,
      tenantId,
      companyId,
      fieldKey: 'phone',
      label: 'Phone Number',
      isRequired: false,
      isEnabled: true,
      displayOrder: 4,
      isSystem: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: `fld_cfg_${companyId}_company_id`,
      tenantId,
      companyId,
      fieldKey: 'companyId',
      label: 'Company',
      isRequired: true,
      isEnabled: true,
      displayOrder: 5,
      isSystem: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: `fld_cfg_${companyId}_dept_id`,
      tenantId,
      companyId,
      fieldKey: 'departmentId',
      label: 'Department',
      isRequired: true,
      isEnabled: true,
      displayOrder: 6,
      isSystem: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: `fld_cfg_${companyId}_desig_id`,
      tenantId,
      companyId,
      fieldKey: 'designationId',
      label: 'Designation',
      isRequired: true,
      isEnabled: true,
      displayOrder: 7,
      isSystem: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: `fld_cfg_${companyId}_loc_id`,
      tenantId,
      companyId,
      fieldKey: 'locationId',
      label: 'Work Location',
      isRequired: false,
      isEnabled: true,
      displayOrder: 8,
      isSystem: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: `fld_cfg_${companyId}_joining_date`,
      tenantId,
      companyId,
      fieldKey: 'joiningDate',
      label: 'Date of Joining',
      isRequired: true,
      isEnabled: true,
      displayOrder: 9,
      isSystem: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: `fld_cfg_${companyId}_emp_type`,
      tenantId,
      companyId,
      fieldKey: 'employmentType',
      label: 'Employment Type',
      isRequired: true,
      isEnabled: true,
      displayOrder: 10,
      isSystem: true,
      createdAt: now,
      updatedAt: now,
    },
  ];
}

export function getDefaultDocumentRequirements(
  tenantId: string,
  companyId: string,
): OnboardingDocumentRequirementDto[] {
  const now = new Date();
  return [
    {
      id: `doc_req_${companyId}_id_proof`,
      tenantId,
      companyId,
      documentType: 'id_proof',
      name: 'Government ID Proof',
      description: 'National ID, Passport, or Driver License',
      isRequired: true,
      verificationRequired: true,
      expiryTracking: false,
      displayOrder: 1,
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: `doc_req_${companyId}_edu_cert`,
      tenantId,
      companyId,
      documentType: 'educational_certificates',
      name: 'Degree & Educational Certificates',
      description: 'Highest degree completion certificates',
      isRequired: true,
      verificationRequired: true,
      expiryTracking: false,
      displayOrder: 2,
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: `doc_req_${companyId}_relieving`,
      tenantId,
      companyId,
      documentType: 'experience_letters',
      name: 'Previous Employment Relieving Letters',
      description: 'Relieving & experience letters from past employers',
      isRequired: false,
      verificationRequired: true,
      expiryTracking: false,
      displayOrder: 3,
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: `doc_req_${companyId}_bank`,
      tenantId,
      companyId,
      documentType: 'bank_details',
      name: 'Bank Account Passbook / Cancelled Cheque',
      description: 'Bank details for salary processing',
      isRequired: true,
      verificationRequired: true,
      expiryTracking: false,
      displayOrder: 4,
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
  ];
}

export function getDefaultChecklistTemplates(
  tenantId: string,
  companyId: string,
): OnboardingChecklistTemplateDto[] {
  const now = new Date();
  return [
    {
      id: `chk_tpl_${companyId}_welcome`,
      tenantId,
      companyId,
      name: 'Send Welcome Email',
      description: 'Send onboarding email and first-day details to new hire',
      stageKey: 'preboarding',
      assigneeType: 'hr',
      dueOffsetDays: -3,
      isRequired: true,
      displayOrder: 1,
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: `chk_tpl_${companyId}_hardware`,
      tenantId,
      companyId,
      name: 'Prepare IT Hardware & Accounts',
      description: 'Provision laptop, email account, and access rights',
      stageKey: 'preboarding',
      assigneeType: 'it_admin',
      dueOffsetDays: -1,
      isRequired: true,
      displayOrder: 2,
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: `chk_tpl_${companyId}_submit_docs`,
      tenantId,
      companyId,
      name: 'Submit Personal & Banking Information',
      description: 'Upload required documents and enter bank details',
      stageKey: 'documents',
      assigneeType: 'employee',
      dueOffsetDays: 1,
      isRequired: true,
      displayOrder: 3,
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: `chk_tpl_${companyId}_verify_docs`,
      tenantId,
      companyId,
      name: 'Verify Submitted Documents',
      description: 'Review and verify identity and background documents',
      stageKey: 'documents',
      assigneeType: 'hr',
      dueOffsetDays: 3,
      isRequired: true,
      displayOrder: 4,
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: `chk_tpl_${companyId}_induction`,
      tenantId,
      companyId,
      name: 'Team Introduction & Induction Session',
      description: 'Conduct welcome meeting and introduce team buddy',
      stageKey: 'induction',
      assigneeType: 'manager',
      dueOffsetDays: 1,
      isRequired: true,
      displayOrder: 5,
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
  ];
}

export function getDefaultConversionSettings(
  tenantId: string,
  companyId: string,
): OnboardingConversionSettingsDto {
  const now = new Date();
  return {
    id: `conv_sett_${companyId}`,
    tenantId,
    companyId,
    autoConvertOnJoining: false,
    requireDocumentVerification: true,
    requireChecklistCompletion: true,
    employeeIdPrefix: 'EMP-',
    defaultEmploymentStatus: 'probation',
    createdAt: now,
    updatedAt: now,
  };
}
