/**
 * Google Material Symbols Outlined Mapping Registry
 *
 * Maps canonical BEZENT icon concepts and historical aliases to their
 * corresponding Google Material Symbols Outlined font ligatures.
 * Governed by ADR-015 (docs/architecture/ADRs.md#adr-015).
 */

export const MATERIAL_SYMBOLS_MAP: Record<string, string> = {
  // Global & Core Navigation
  dashboard: 'dashboard',
  overview: 'dashboard',
  tasks: 'checklist',
  task: 'checklist',
  checklist: 'checklist',
  'my tasks': 'checklist',
  approvals: 'task_alt',
  approval: 'task_alt',
  task_alt: 'task_alt',
  calendar: 'calendar_today',
  events: 'calendar_today',
  schedule: 'calendar_today',
  notes: 'note_alt',
  description: 'description',
  notifications: 'notifications',
  bell: 'notifications',
  search: 'search',
  filter: 'tune',
  filter_list: 'tune',
  announcements: 'campaign',
  campaign: 'campaign',
  help: 'help',
  help_outline: 'help',
  helpcircle: 'help',
  helpCircle: 'help',
  help_circle: 'help',
  settings: 'settings',
  hrsettings: 'manage_accounts',
  hrSettings: 'manage_accounts',
  crmsettings: 'settings',
  pmsettings: 'settings',
  customize: 'settings',
  operations: 'hub',
  hub: 'hub',
  reports: 'bar_chart',
  analytics: 'bar_chart',
  documents: 'folder',
  docs: 'folder',
  document: 'description',
  folders: 'folder',
  folder: 'folder',
  assets: 'inventory_2',
  inventory_2: 'inventory_2',
  requests: 'assignment',
  assignment: 'assignment',
  more: 'more_horiz',
  more_horiz: 'more_horiz',
  moreh: 'more_horiz',
  home: 'home',
  add: 'add',
  plus: 'add',
  plussign: 'add',
  plusSign: 'add',
  edit: 'edit',
  delete: 'delete',
  security: 'security',
  sop: 'menu_book',

  // Shell Utilities & Micro-actions
  whatsnew: 'new_releases',
  whatsNew: 'new_releases',
  "what's new": 'new_releases',
  'whats new': 'new_releases',
  badgeinfo: 'new_releases',
  badge_info: 'new_releases',
  explore: 'explore',
  rocket: 'explore',
  apps: 'apps',
  grid: 'apps',
  grid2x2: 'apps',
  'quick actions': 'apps',
  sparkles: 'auto_awesome',
  ai: 'auto_awesome',
  gemini: 'auto_awesome',
  chevronleft: 'chevron_left',
  chevronLeft: 'chevron_left',
  chevronright: 'chevron_right',
  chevronRight: 'chevron_right',
  chevrondown: 'keyboard_arrow_down',
  chevronDown: 'keyboard_arrow_down',
  arrowleft: 'arrow_back',
  arrowLeft: 'arrow_back',
  arrowright: 'arrow_forward',
  arrowRight: 'arrow_forward',
  moon: 'dark_mode',
  sun: 'light_mode',
  close: 'close',
  check: 'check',
  clock: 'schedule',
  warning: 'warning',
  menu: 'menu',
  hamburger: 'menu',
  pin: 'push_pin',

  // HRMS Concepts
  employees: 'group',
  groups: 'group',
  people: 'group',
  directory: 'group',
  'employee directory': 'group',
  employeedirectory: 'group',
  workforce: 'groups',
  onboarding: 'person_add',
  onboard: 'person_add',
  person_add: 'person_add',
  leave: 'event_busy',
  'leave tracker': 'event_busy',
  event_busy: 'event_busy',
  attendance: 'co_present',
  timetracker: 'schedule',
  timeTracker: 'schedule',
  'time tracker': 'schedule',
  timer: 'schedule',
  shifts: 'date_range',
  'shift management': 'date_range',
  date_range: 'date_range',
  timesheets: 'pending_actions',
  payroll: 'payments',
  compensation: 'monetization_on',
  benefits: 'card_membership',
  performance: 'trending_up',
  perf: 'trending_up',
  trending_up: 'trending_up',
  goals: 'flag',
  reviews: 'rate_review',
  learning: 'school',
  school: 'school',
  career: 'route',
  route: 'route',
  recruitment: 'work',
  recruit: 'work',
  work: 'work',
  candidates: 'badge',
  badge: 'badge',
  interviews: 'event_available',
  event_available: 'event_available',
  jobopenings: 'work',
  jobOpenings: 'work',
  'job openings': 'work',
  offers: 'mark_email_read',
  organization: 'account_tree',
  account_tree: 'account_tree',

  // CRM Concepts
  leads: 'person_search',
  contacts: 'contacts',
  accounts: 'domain',
  deals: 'handshake',
  pipeline: 'view_kanban',
  campaigns: 'campaign',
  products: 'inventory',
  quotes: 'request_quote',
  invoices: 'receipt_long',
  support: 'support_agent',

  // Project Management (PM) Concepts
  projects: 'folder_special',
  planning: 'calendar_view_week',
  milestones: 'flag',
  risks: 'gpp_maybe',
  issues: 'report_problem',
  changes: 'published_with_changes',
  delivery: 'local_shipping',
};

/**
 * Resolves any semantic or legacy icon name to its canonical
 * Google Material Symbols Outlined ligature string.
 * Falls back to 'dashboard' if unknown.
 */
export function getMaterialSymbolGlyph(name: string): string {
  const normalized = (name || '').toLowerCase().trim();
  return MATERIAL_SYMBOLS_MAP[name] ?? MATERIAL_SYMBOLS_MAP[normalized] ?? 'dashboard';
}
