CREATE TABLE IF NOT EXISTS `employee_attendance` (
  `id` varchar(64) NOT NULL,
  `tenant_id` varchar(64) NOT NULL,
  `company_id` varchar(64) NOT NULL,
  `employee_id` varchar(64) NOT NULL,
  `date` varchar(10) NOT NULL,
  `check_in_time` varchar(10),
  `check_out_time` varchar(10),
  `status` enum('present','absent','half_day','on_leave','holiday') NOT NULL DEFAULT 'present',
  `work_location` varchar(100) NOT NULL DEFAULT 'office',
  `notes` varchar(500),
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_emp_att_tenant_company` (`tenant_id`, `company_id`),
  INDEX `idx_emp_att_employee` (`employee_id`),
  INDEX `idx_emp_att_date` (`date`),
  UNIQUE INDEX `idx_emp_att_emp_date` (`tenant_id`, `company_id`, `employee_id`, `date`),
  CONSTRAINT `fk_emp_att_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
  CONSTRAINT `fk_emp_att_employee` FOREIGN KEY (`employee_id`) REFERENCES `employees` (`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `employee_leave_balances` (
  `id` varchar(64) NOT NULL,
  `tenant_id` varchar(64) NOT NULL,
  `company_id` varchar(64) NOT NULL,
  `employee_id` varchar(64) NOT NULL,
  `leave_type` enum('annual','sick','casual','unpaid') NOT NULL,
  `total_days` int NOT NULL DEFAULT 0,
  `used_days` int NOT NULL DEFAULT 0,
  `pending_days` int NOT NULL DEFAULT 0,
  `year` int NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_emp_leave_bal_tenant_comp` (`tenant_id`, `company_id`),
  INDEX `idx_emp_leave_bal_employee` (`employee_id`),
  UNIQUE INDEX `idx_emp_leave_bal_type_year` (`tenant_id`, `company_id`, `employee_id`, `leave_type`, `year`),
  CONSTRAINT `fk_emp_leave_bal_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
  CONSTRAINT `fk_emp_leave_bal_employee` FOREIGN KEY (`employee_id`) REFERENCES `employees` (`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `employee_leave_requests` (
  `id` varchar(64) NOT NULL,
  `tenant_id` varchar(64) NOT NULL,
  `company_id` varchar(64) NOT NULL,
  `employee_id` varchar(64) NOT NULL,
  `leave_type` enum('annual','sick','casual','unpaid') NOT NULL,
  `start_date` varchar(10) NOT NULL,
  `end_date` varchar(10) NOT NULL,
  `total_days` int NOT NULL,
  `reason` varchar(500) NOT NULL,
  `status` enum('pending','approved','rejected','cancelled') NOT NULL DEFAULT 'pending',
  `reviewed_by_user_id` varchar(64),
  `rejection_reason` varchar(500),
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_emp_leave_req_tenant_comp` (`tenant_id`, `company_id`),
  INDEX `idx_emp_leave_req_employee` (`employee_id`),
  INDEX `idx_emp_leave_req_status` (`status`),
  INDEX `idx_emp_leave_req_dates` (`start_date`, `end_date`),
  CONSTRAINT `fk_emp_leave_req_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
  CONSTRAINT `fk_emp_leave_req_employee` FOREIGN KEY (`employee_id`) REFERENCES `employees` (`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `employee_timesheets` (
  `id` varchar(64) NOT NULL,
  `tenant_id` varchar(64) NOT NULL,
  `company_id` varchar(64) NOT NULL,
  `employee_id` varchar(64) NOT NULL,
  `date` varchar(10) NOT NULL,
  `project_name` varchar(150) NOT NULL,
  `task_description` varchar(500) NOT NULL,
  `hours` int NOT NULL,
  `status` enum('draft','submitted','approved','rejected') NOT NULL DEFAULT 'draft',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_emp_timesheet_tenant_comp` (`tenant_id`, `company_id`),
  INDEX `idx_emp_timesheet_employee` (`employee_id`),
  INDEX `idx_emp_timesheet_date` (`date`),
  INDEX `idx_emp_timesheet_status` (`status`),
  CONSTRAINT `fk_emp_timesheet_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
  CONSTRAINT `fk_emp_timesheet_employee` FOREIGN KEY (`employee_id`) REFERENCES `employees` (`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `employee_requests` (
  `id` varchar(64) NOT NULL,
  `tenant_id` varchar(64) NOT NULL,
  `company_id` varchar(64) NOT NULL,
  `employee_id` varchar(64) NOT NULL,
  `request_type` enum('profile_change','attendance_regularization','document_request','general_service') NOT NULL,
  `subject` varchar(200) NOT NULL,
  `details` json NOT NULL,
  `status` enum('pending','approved','rejected','cancelled') NOT NULL DEFAULT 'pending',
  `reviewer_notes` varchar(500),
  `reviewed_by_user_id` varchar(64),
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_emp_requests_tenant_comp` (`tenant_id`, `company_id`),
  INDEX `idx_emp_requests_employee` (`employee_id`),
  INDEX `idx_emp_requests_type_status` (`request_type`, `status`),
  CONSTRAINT `fk_emp_requests_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
  CONSTRAINT `fk_emp_requests_employee` FOREIGN KEY (`employee_id`) REFERENCES `employees` (`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `employee_tasks` (
  `id` varchar(64) NOT NULL,
  `tenant_id` varchar(64) NOT NULL,
  `company_id` varchar(64) NOT NULL,
  `employee_id` varchar(64) NOT NULL,
  `title` varchar(200) NOT NULL,
  `description` varchar(500),
  `due_date` varchar(10),
  `priority` enum('low','medium','high') NOT NULL DEFAULT 'medium',
  `status` enum('pending','in_progress','completed') NOT NULL DEFAULT 'pending',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_emp_tasks_tenant_comp` (`tenant_id`, `company_id`),
  INDEX `idx_emp_tasks_employee` (`employee_id`),
  INDEX `idx_emp_tasks_status` (`status`),
  CONSTRAINT `fk_emp_tasks_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
  CONSTRAINT `fk_emp_tasks_employee` FOREIGN KEY (`employee_id`) REFERENCES `employees` (`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `employee_notifications` (
  `id` varchar(64) NOT NULL,
  `tenant_id` varchar(64) NOT NULL,
  `company_id` varchar(64) NOT NULL,
  `employee_id` varchar(64) NOT NULL,
  `title` varchar(200) NOT NULL,
  `message` varchar(500) NOT NULL,
  `type` enum('info','success','warning','action_required') NOT NULL DEFAULT 'info',
  `is_read` boolean NOT NULL DEFAULT FALSE,
  `link` varchar(200),
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_emp_notif_tenant_comp` (`tenant_id`, `company_id`),
  INDEX `idx_emp_notif_employee` (`employee_id`),
  INDEX `idx_emp_notif_read` (`is_read`),
  INDEX `idx_emp_notif_created` (`created_at`),
  CONSTRAINT `fk_emp_notif_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
  CONSTRAINT `fk_emp_notif_employee` FOREIGN KEY (`employee_id`) REFERENCES `employees` (`id`)
);
